name: ReportSystem-Spigot
version: 1.0
main: fr.springg.reportsystem.Main
author: Spring_g
description: Système de report avec MySQL
commands:
  report:
    permission: report.use
    description: Signaler un joueur.